version: '3.9'
services:
  app:
    container_name: xsis-api
    build: .
    ports:
      - 1000:1000
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USR=${POSTGRES_USR}
      - POSTGRES_PWD=${POSTGRES_PWD}
      - POSTGRES_PRT=
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
      - POSTGRES_TIMEZONE=${POSTGRES_TIMEZONE}
      - APP_PORT=${APP_PORT}
    volumes:
      - .:/apps
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql